"""add_google_flood_stations

Revision ID: 3fba287c82e0
Revises: add_dust_warning
Create Date: 2026-02-03 21:44:07.895402

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '3fba287c82e0'
down_revision = 'add_dust_warning'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_flood_gauge',
    sa.Column('gauge_id', sa.String(length=256), nullable=False),
    sa.Column('site_name', sa.String(length=512), nullable=True),
    sa.Column('river', sa.String(length=256), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('quality_verified', sa.Boolean(), nullable=True),
    sa.Column('has_model', sa.Boolean(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('gauge_id')
    )
    with op.batch_alter_table('google_flood_gauge', schema=None) as batch_op:
        batch_op.create_index('idx_google_flood_gauge_geom', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})

    op.create_table('google_flood_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gauge_id', sa.String(length=256), nullable=False),
    sa.Column('issued_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('forecast_trend', sa.String(length=32), nullable=True),
    sa.Column('quality_verified', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('forecast_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_change_lower', sa.Float(), nullable=True),
    sa.Column('value_change_upper', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gauge_id'], ['google_flood_gauge.gauge_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gauge_id', 'issued_time', name='unique_flood_status')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_flood_status')
    with op.batch_alter_table('google_flood_gauge', schema=None) as batch_op:
        batch_op.drop_index('idx_google_flood_gauge_geom', postgresql_using='gist')

    op.drop_table('google_flood_gauge')
    # ### end Alembic commands ###
